name = "canvas-lms-chatbot"
compatibility_date = "2023-06-28"
compatibility_flags = ["nodejs_compat"]

# Configure Cloudflare Pages with Next.js
[build]
command = "npm install --legacy-peer-deps && npm run build && npx @cloudflare/next-on-pages"

[site]
bucket = ".vercel/output/static"

# Pages specific configuration
pages_build_output_dir = ".vercel/output/static"

# Configure environment variables
[vars]
NODE_VERSION = "18.18.0"
